services:
   db:
    restart: always
    image: mysql:5.7.24
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: localuser
      MYSQL_PASSWORD: localpass
      MYSQL_DATABASE: localdb
    volumes:
      - ./persistence/init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password
      PMA_ABSOLUTE_URI: http://localhost:8080/
      PMA_AUTH_TYPE: config
      PMA_CHARSET: utf8mb4
      PHP_CHARSET: utf8mb4
    ports:
      - "8080:80"
    volumes:
      - ./config/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    depends_on:
      - db
